package com.boothlock.boothlock_server.booth.controller;

import com.boothlock.boothlock_server.booth.domain.BoothEntity;
import com.boothlock.boothlock_server.booth.domain.StaffAccountEntity;
import com.boothlock.boothlock_server.booth.domain.StaffRole;
import com.boothlock.boothlock_server.booth.repository.BoothRepository;
import com.boothlock.boothlock_server.booth.repository.StaffAccountRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.factory.PasswordEncoderFactories;
import org.springframework.test.web.servlet.MockMvc;
import tools.jackson.databind.ObjectMapper;

import java.time.LocalDateTime;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
class BoothInfoApiTests {

    @Autowired MockMvc mockMvc;
    @Autowired ObjectMapper objectMapper;
    @Autowired StaffAccountRepository staffAccountRepository;
    @Autowired BoothRepository boothRepository;
    @Autowired JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("""
                create table if not exists booth_table (
                    id bigint generated by default as identity primary key,
                    booth_id bigint not null,
                    label varchar(20) not null,
                    table_token varchar(64) not null unique,
                    status varchar(20) not null default 'EMPTY'
                )
                """);
        jdbcTemplate.update("delete from booth_table");
        staffAccountRepository.deleteAll();
        boothRepository.deleteAll();

        BoothEntity booth = boothRepository.save(new BoothEntity("운영 부스", "은행 1234", "10:00~20:00"));
        BoothEntity otherBooth = boothRepository.save(new BoothEntity("다른 부스", "은행 5678", null));
        String hash = PasswordEncoderFactories.createDelegatingPasswordEncoder().encode("correct-password");
        staffAccountRepository.save(new StaffAccountEntity(
                booth, "booth-admin", hash, LocalDateTime.of(2026, 8, 13, 12, 0), StaffRole.ADMIN));
        jdbcTemplate.update(
                "insert into booth_table (booth_id, label, table_token, status) values (?, ?, ?, ?)",
                booth.getId(), "A-1", "token-a-1", "EMPTY");
        jdbcTemplate.update(
                "insert into booth_table (booth_id, label, table_token, status) values (?, ?, ?, ?)",
                booth.getId(), "A-2", "token-a-2", "OCCUPIED");
        jdbcTemplate.update(
                "insert into booth_table (booth_id, label, table_token, status) values (?, ?, ?, ?)",
                otherBooth.getId(), "B-1", "token-b-1", "EMPTY");
    }

    @AfterEach
    void tearDown() {
        jdbcTemplate.update("delete from booth_table");
        staffAccountRepository.deleteAll();
        boothRepository.deleteAll();
    }

    @Test
    void returnsOnlyAuthenticatedStaffBooth() throws Exception {
        String token = login("booth-admin", "correct-password");

        mockMvc.perform(get("/api/v1/admin/booth").header("Authorization", "Bearer " + token))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.name").value("운영 부스"))
                .andExpect(jsonPath("$.bankAccount").value("은행 1234"))
                .andExpect(jsonPath("$.operatingHours").value("10:00~20:00"))
                .andExpect(jsonPath("$.tableCount").value(2))
                .andExpect(jsonPath("$.isOpen").value(true));
    }

    @Test
    void rejectsRequestWithoutToken() throws Exception {
        mockMvc.perform(get("/api/v1/admin/booth"))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.error.code").value("UNAUTHORIZED"));
    }

    @Test
    void forbidsSuperAdminWithoutBooth() throws Exception {
        String hash = PasswordEncoderFactories.createDelegatingPasswordEncoder().encode("correct-password");
        staffAccountRepository.save(new StaffAccountEntity(
                null, "super-admin", hash, LocalDateTime.of(2026, 8, 13, 12, 0), StaffRole.SUPER_ADMIN));
        String token = login("super-admin", "correct-password");

        mockMvc.perform(get("/api/v1/admin/booth").header("Authorization", "Bearer " + token))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.error.code").value("FORBIDDEN"));
    }

    private String login(String loginId, String password) throws Exception {
        String response = mockMvc.perform(post("/api/v1/admin/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new Credentials(loginId, password))))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();
        return objectMapper.readTree(response).get("accessToken").asText();
    }

    private record Credentials(String loginId, String password) {
    }
}
